// Translations
const translations = {
    "en": {
        "navCalculator": "Calculator",
        "navCompare": "Compare",
        "navCalendar": "Calendar",
        "accountLogOut": "Log out",
        "startButton": "Get Started",
        "heroH1": "NutriCost is a powerful tool for improving the quality of your life",
        "heroP1": "Track calories, compare meals, calculate cost of food and more...",
        "heroBut1": "Start now",
        "heroH2": "Eat smart. Spend smart.",
        "heroP2": "Use this powerful tools:",
        "heroToolBox1": "Calculator instantly calculate calories of your meals <br>⮕",
        "heroToolBox2": "Meal comparator helps find the best meal for your goals <br>⮕",
        "heroToolBox3": "History calendar shows your past day or week nutrition <br>⮕",
        "conceptionH1": "NutriCost is a new look at your nutrition",
        "conceptionP1": "Our tools are just the beginning. NutriCost is built on a philosophy of smart food and budgeting",
        "conceptionBut1": "Try now",
        "conceptionH2": "Our mission",
        "conceptionLi1": "Make healthy living simple and clear",
        "conceptionLi2": "Help you find balance without strict diets",
        "conceptionLi3": "Give you tools, not restrictions",
        "conceptionLi4": "Support your progress step by step",
        "conceptionH3": "What we believe in",
        "conceptionLi5": "Simplicity — health should be realistic and practical",
        "conceptionLi6": "Honesty — no myths, no marketing lies",
        "conceptionLi7": "Consistency — small steps lead to real change",
        "conceptionLi8": "Well-being — take care of both body and mind",
        "conceptionH4": "Who this platform is for",
        "conceptionLi9": "People who want to feel and perform better",
        "conceptionLi10": "Anyone looking to build healthy eating habits",
        "conceptionLi11": "Those who value discipline and progress",
        "conceptionLi12": "Anyone ready to take control of their health",
        "featuresH1": "Calorie and budget calculator",
        "featuresP1": "Instant calculation and planning of your meals",
        "featuresBut1": "Calculating calories",
        "featuresBut2": "Changing ingredients",
        "featuresBut3": "Adding to calendar",
        "featuresH2": "Make informed decisions with meal comparator",
        "featuresP2": "Compare the two dishes based on all parameters",
        "featuresBut4": "Choosing food",
        "featuresBut5": "Comparing meals",
        "featuresBut6": "Calculating the pros",
        "featuresH3": "Your personal food diary",
        "featuresP3": "Track your progress in a convenient format",
        "featuresBut7": "View months",
        "featuresBut8": "Food history by day",
        "featuresBut9": "Results for the week",
        "finalActionH1": "Take complete control of your health",
        "finalActionP1": "Get access to all NutriCost tools right now",
        "finalActionBut1": "Try for free",
        "footerP1": "Your indispensable assistant in the world of healthy eating",
        "footerP2": "Features",
        "footerA1": "Calculator",
        "footerA2": "Comparator",
        "footerA3": "Calendar",
        "footerP3": "Connect",
        "footerA4": "GitHub",
        "footerA5": "Linkedin",
        "footerP4": "&copy; 2025 NutriCost. All rights reserved.",

        //Calculator, compataror, calendar page
        "unitGramm": "g",
        "unitKcal": "kcal",
        "calcIngridientName": "Name of ingredient...",
        "calcDatabaseSearch": "Search...",
        "calcIngridientWeight": "Weight (gramms)...",
        "ingredient1": "Ingredient <br> №1",
        "ingredient1NameP": "Name",
        "ingredientChoose": "Choose",
        "ingredient1WeightP": "Weight",
        "ingredient1MacroBalanceP": "Macro balance on 100g",
        "calcIngridientProteins": "Proteins...",
        "calcIngridientFats": "Fats...",
        "calcIngridientCarbohydrates": "Carbohydrates...",
        "ingredient1CostP": "Cost on 100g",
        "calcIngridientCost": "Cost ($)...",
        "ingredient2": "Ingredient №2",
        "ingredient3": "Ingredient №3",
        "calcResults": "Results",
        "calcResultName": "Name:",
        "calcResultWeight": "Weight:",
        "calcResultProteins": "Proteins:",
        "calcResultFats": "Fats:",
        "calcResultCarbohydrates": "Carbohydrates:",
        "calcResultEnergy": "Energy:",
        "calcCalorieDensity": "Calorie density:",
        "calcResultCost": "Cost:",
        "calcChooseMeal": "Choose meal",
        "calcSaveMeal": "Save meal",
        "calcInputMeal": "Name of meal...",
        "calcSaveMeal2": "Save",
        "calcChangeIngredient": "Change ingredient",
        "calcConfirm": "Are you sure?",
        "calcConfirmYes": "Yes",
        "calcConfirmNo": "No",
        "calcSaveIngredient": "Save ingredient",
        "calcDeleteIngredient": "Delete ingredient",
        "calcAddToCalendar": "Add to calendar",
        "compChooseIngredient": "Choose ingredient",
        "compEnergy": "Energy on 100g:",
        "compCalorieDensity": "Calorie density on 100g:",
        "calendarMon": "Mo",
        "calendarTue": "Tu",
        "calendarWed": "We",
        "calendarThu": "Th",
        "calendarFri": "Fr",
        "calendarSat": "Sa",
        "calendarSun": "Su",

        // Login page
        "accountSignUp": "Sign up",
        "accountLogin": "Log in",
        "accLogin": "Enter your login...",
        "accPassword": "Enter your password...",
    },
    "uk": {
        "navCalculator": "Калькулятор",
        "navCompare": "Порівняти",
        "navCalendar": "Календар",
        "startButton": "Почати",
        "accountLogOut": "Вийти",
        "heroH1": "NutriCost – це потужний інструмент для покращення якості вашого життя",
        "heroP1": "Відстежуйте калорії, порівнюйте страви, розраховуйте вартість їжі та багато іншого...",
        "heroBut1": "Почніть зараз",
        "heroH2": "Харчуйтеся розумно. Витрачайте розумно.",
        "heroP2": "Використовуйте ці потужні інструменти:",
        "heroToolBox1": "Калькулятор миттєво розраховує калорії ваших страв <br>⮕",
        "heroToolBox2": "Порівнювач страв допоможе знайти найкращу страву для ваших цілей <br>⮕",
        "heroToolBox3": "Календар показує ваше харчування за минулий день або тиждень <br>⮕",
        "conceptionH1": "NutriCost — це новий погляд на ваше харчування",
        "conceptionP1": "Наші інструменти – це лише початок. NutriCost побудований на філософії розумного харчування та бюджету.",
        "conceptionBut1": "Спробуйте зараз",
        "conceptionH2": "Наша місія",
        "conceptionLi1": "Зробити здоровий спосіб життя простим та зрозумілим",
        "conceptionLi2": "Допомогти вам знайти баланс без суворих дієт",
        "conceptionLi3": "Дати вам інструменти, а не обмеження",
        "conceptionLi4": "Підтримати ваш прогрес крок за кроком",
        "conceptionH3": "У що ми віримо",
        "conceptionLi5": "Простота — здоров'я має бути реалістичним та практичним",
        "conceptionLi6": "Чесність — жодних міфів, жодної маркетингової брехні",
        "conceptionLi7": "Послідовність — маленькі кроки ведуть до реальних змін",
        "conceptionLi8": "Благополуччя — піклуйтеся і про тіло, і про розум",
        "conceptionH4": "Для кого ця платформа:",
        "conceptionLi9": "Людей, які хочуть почуватися краще та працювати краще",
        "conceptionLi10": "Усіх, хто хоче сформувати здорові харчові звички",
        "conceptionLi11": "Тих, хто цінує дисципліну та прогрес",
        "conceptionLi12": "Кожного, хто готовий взяти під контроль своє здоров'я",
        "featuresH1": "Калькулятор калорій та бюджету",
        "featuresP1": "Миттєвий розрахунок та планування ваших страв",
        "featuresBut1": "Розрахунок калорій",
        "featuresBut2": "Зміна інгредієнтів",
        "featuresBut3": "Додавання до календаря",
        "featuresH2": "Приймайте обґрунтовані рішення за допомогою порівнювача страв",
        "featuresP2": "Порівняйте дві страви за всіма параметрами",
        "featuresBut4": "Вибір їжі",
        "featuresBut5": "Порівняння страв",
        "featuresBut6": "Розрахунок переваг",
        "featuresH3": "Ваш особистий щоденник харчування",
        "featuresP3": "Відстежуйте свій прогрес у зручному форматі",
        "featuresBut7": "Перегляд місяців",
        "featuresBut8": "Історія їжі по днях",
        "featuresBut9": "Результати за тиждень",
        "finalActionH1": "Візьміть своє здоров'я під повний контроль",
        "finalActionP1": "Отримайте доступ до всіх інструментів NutriCost прямо зараз",
        "finalActionBut1": "Спробуйте безкоштовно",
        "footerP1": "Ваш незамінний помічник у світі здорового харчування",
        "footerP2": "Інструменти",
        "footerA1": "Калькулятор",
        "footerA2": "Порівнювач",
        "footerA3": "Календар",
        "footerP3": "Соцмережи",
        "footerA4": "GitHub",
        "footerA5": "Linkedin",
        "footerP4": "&copy; 2025 NutriCost. Усі права захищено.",

        //Calculator, compataror, calendar page
        "unitGramm": "г",
        "unitKcal": "ккал",
        "calcIngridientName": "Назва інгредієнта...",
        "calcDatabaseSearch": "Пошук...",
        "calcIngridientWeight": "Вага (грамм)...",
        "ingredient1": "Інгредієнт <br> №1",
        "ingredient1NameP": "Ім'я",
        "ingredientChoose": "Вибрати",
        "ingredient1WeightP": "Вага",
        "ingredient1MacroBalanceP": "Макро баланс на 100г",
        "calcIngridientProteins": "Білки...",
        "calcIngridientFats": "Жири...",
        "calcIngridientCarbohydrates": "Вуглеводи...",
        "ingredient1CostP": "Ціна на 100г",
        "calcIngridientCost": "Ціна ($)...",
        "ingredient2": "Інгредієнт №2",
        "ingredient3": "Інгредієнт №3",
        "calcResults": "Результати",
        "calcResultName": "Ім'я:",
        "calcResultWeight": "Вага:",
        "calcResultProteins": "Білки:",
        "calcResultFats": "Жири:",
        "calcResultCarbohydrates": "Вуглеводи:",
        "calcResultEnergy": "Енергія:",
        "calcCalorieDensity": "Щільність калорій:",
        "calcResultCost": "Ціна:",
        "calcChooseMeal": "Виберіть страву",
        "calcSaveMeal": "Зберегти страву",
        "calcInputMeal": "Ім'я страви...",
        "calcSaveMeal2": "Зберегти",
        "calcChangeIngredient": "Змінити інгредієнт",
        "calcConfirm": "Ви впевнені?",
        "calcConfirmYes": "Так",
        "calcConfirmNo": "Ні",
        "calcSaveIngredient": "Зберегти інгредієнт",
        "calcDeleteIngredient": "Видалити інгредієнт",
        "calcAddToCalendar": "Додати до календаря",
        "compChooseIngredient": "Виберіть інгредієнт",
        "compEnergy": "Енергія на 100г:",
        "compCalorieDensity": "Щільність калорій на 100г",
        "calendarMon": "Пн",
        "calendarTue": "Вт",
        "calendarWed": "Ср",
        "calendarThu": "Чт",
        "calendarFri": "Пт",
        "calendarSat": "Сб",
        "calendarSun": "Нд",

        // Login page
        "accountSignUp": "Реєстрація",
        "accountLogin": "Увійти",
        "accLogin": "Введіть свій логін...",
        "accPassword": "Введіть свій пароль...",
    }
}


// Language change logic
function setLanguage(lang) {
    const elements = document.querySelectorAll('[data-key]')
    elements.forEach(element => {
        const key = element.dataset.key
        if (translations[lang] && translations[lang][key]) {
            const translation = translations[lang][key]
            element.innerHTML = translation
        }
    })
    const elementsPlaceholder = document.querySelectorAll('[data-key-placeholder]')
    elementsPlaceholder.forEach(element => {
        const key = element.dataset.keyPlaceholder
        if (translations[lang] && translations[lang][key]) {
            element.placeholder = translations[lang][key]
        }
    })
}